export const funFacts = [
  "Smiling—even when you don’t feel like it—can trick your brain into feeling happier.",
  "Gratitude journaling for just 2 minutes improves mood for the next 24 hours.",
  "Looking at nature for 40 seconds boosts focus and reduces stress.",
  "Your brain releases dopamine when you complete a small task—checklists work!",
  "Writing your thoughts down reduces stress by up to 30%.",
  "Slow breathing (4 seconds inhale, 6 seconds exhale) lowers anxiety instantly.",
  "A warm shower relaxes your muscles and helps stabilize mood.",
  "Touching water (washing hands or face) resets your nervous system.",
  "Watching the sky for 60 seconds activates your calmness center.",
  "Soft instrumental music slows your heartbeat and reduces stress.",
  "Drinking enough water boosts mood by improving oxygen flow to the brain.",
  "Even mild dehydration can cause irritability and tiredness.",
  "Eating nuts like walnuts and almonds supports brain health and improves focus.",
  "Dark chocolate increases endorphins—your natural feel-good chemicals.",
  "Bananas contain tryptophan which helps improve mood.",
  "A 10-minute walk improves mood for up to 2 hours.",
  "Stretching reduces both physical and emotional tension.",
  "Sunlight exposure for just 5 minutes boosts serotonin—your happiness hormone.",
  "Dancing for 3 minutes can instantly lift your spirits.",
  "Light exercise improves sleep and reduces anxiety symptoms.",
  "Reading for 6 minutes before bed reduces stress by 68%.",
  "A short nap of 10–20 minutes can boost mood and productivity.",
  "Avoiding screens 30 minutes before bed leads to better sleep quality.",
  "Lavender scent helps lower stress and promote calm sleep.",
  "Regular sleep schedules stabilize emotional well-being.",
  "Learning something new keeps your brain active and improves confidence.",
  "Talking to someone you trust releases oxytocin—the bonding hormone.",
  "Helping someone else boosts your happiness more than receiving help.",
  "Spending time with pets reduces cortisol, the stress hormone.",
  "Cleaning your room for 5 minutes can reduce mental clutter."
];
